{
    'name': "PROJECT Module Update",
    'author': 'Nassim Eloualydy',
    'summary': """project riad""",
    'website': 'http://www.daisy.com',
    'license': 'AGPL-3',
    'description': """ """,
    'version': '1.0',
    'depends': ['sale_management','mail','sale_timesheet','base', 'web','calendar_event'],

    'data': [
        'security/ir.model.access.csv',
        'views/view_form_simplified.xml',
        'views/view_project_edit_project.xml',        
        'views/view_project_tree.xml',
        'views/view_project_task_form.xml',
        'views/view_task_tree.xml',
        'views/view_project_project_kanban.xml',
        'views/view_menu_projet_pv.xml',
        'views/view_resource_resource_calendar_form.xml',
        # 'views/view_move_form.xml',
        # 'views/view_invoice_tree.xml',
        # 'views/view_account_move_kanban.xml',
        # 'views/view_account_payment_register_form.xml',
        'views/project_view_task_kanban_2.xml',
        'views/view_task_search.xml',
        'wizard/purchase_order_wizard.xml',
        'wizard/project_create_sale_order.xml',
        'wizard/merge_task.xml',
        'views/project_menu_action.xml',
        'views/search_view_task.xml',
        'views/project_task_view_gantt.xml',
        'wizard/project_import_ms_project.xml',
        'views/view_project_task_default_tree.xml',
        'views/view_kanban_form_project.xml',
        'views/view_calendar_event.xml',
        # 'views/add_active_menu_project_pv.xml',
        'data/cron.xml',
        'views/view_task_all_calendar.xml',
        'views/view_calendar_generale.xml',
        # 'views/view_kanban_account_journal.xml',
        # 'views/account_view_invoice_bill_tree.xml',
        # 'views/view_out_invoice_tree.xml',
        # 'views/account_view_account_invoice_filter.xml',
        'views/document_view_search.xml',
        'views/base_view_attachment_tree.xml',
        
        'views/base_view_attachment_search.xml',
        'views/view_document_file_kanban.xml',
        # 'views/menu_project.xml',
        # 'views/poject_view_test.xml'

    ],    
        'assets':{
        'web.assets_backend':[
        'projet_riad/static/src/css/main.css',    
        'projet_riad/static/src/js/send_query.js',  
        'projet_riad/static/src/js/group_by_menu.js',  
        'projet_riad/static/src/js/customKanbanViewFollowers.js',    
        'projet_riad/static/src/js/calendar_common_renderer.js',    
        'projet_riad/static/src/js/pivot_group_by_menu.js',    
        'projet_riad/static/src/xml/documents_search_panel.xml',    
        'projet_riad/static/src/js/documents_search_panel.js',    
        'projet_riad/static/src/xml/discuss_sidebar.xml',
        'projet_riad/static/src/xml/search_bar.xml',  
        'projet_riad/static/src/xml/calendar_common_renderer.xml',  

        ]
    },
        
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}

